#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

echo "=== Executing script '.openshift/action_hooks/deploy'..."
cd "${OPENSHIFT_REPO_DIR}"

echo "(*) Prepare booking/local_settings.py file..."
SECRET_KEY=$(cat /dev/urandom | tr -dc 'a-z0-9!@#$%^&*(_=+)-' | fold -w 50 | head -n 1)
cat > "booking/local_settings.py" <<-EOF
	import os

	BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
	STATIC_ROOT = os.path.join(BASE_DIR, 'wsgi/static')

	SECRET_KEY = "$SECRET_KEY"

	DEBUG = False

	ALLOWED_HOSTS = ['*']
EOF
unset SECRET_KEY

echo "(*) Collect static files..."
python "manage.py" collectstatic --noinput

echo "(*) Reset database..."
NOINPUT=true make reset-db

echo "(*) Load app secrets..."
source ~/app-root/data/.app_secrets

echo "(*) Create Django superuser 'admin'..."
export DJANGO_SETTINGS_MODULE="booking.settings"
python - <<-EOF
	from django.contrib.auth.models import User
	u = User.objects.create_user('admin')
	u.set_password('$DJANGO_ADMIN_PASSWORD')
	u.is_superuser=True
	u.is_staff=True
	u.save()
EOF

echo "(*) Unset app secrets..."
unset DJANGO_ADMIN_PASSWORD

echo "(*) Script 'deploy' completed."
