language: python
python: 3.4
install:
  - pip install -r requirements.txt
before_script:
  - python manage.py makemigrations
  - python manage.py migrate
script:
  - pep8 --exclude=migrations .
  - python -Wall manage.py test
