language: python
python: 3.3

install:
- make install
- touch booking/local_settings.py

script:
- make linter
- PYTHON=python NOINPUT=true make reset-db
- PYTHON=python make test

deploy:
  provider: openshift
  user: studenti.galileiana@gmail.com
  password:
    secure: w1wn37zpZG9UjCe4QBng5HJ6a1wBoMuM0xg/imuVNKeDXQjpeBjaTC1/NrfUnUm+wdkx0ujsfEW9aazL0+OpieqlHW5gFyn98XNr1chjncw3f0MDy0zZqvj4grA7rEyDj0YjNsiV7xOUnTPvo6DjGGZFrVJ8x8EpuFev5i+gW3Ou84h61C2rc98QTCA/2YR6a9NyrRgHbzuGTC1I5NhjrDsUZmJy7Wt2f3HnDcbUYUYzuDHpK8HtM8FUPqXGs4k62f+asNazqB0L0gm3MiUWCvuPoFS0iAp8c64tuFp08kCYMsxz2Ra+Kr0D3tvnxWXkSoHRJZ1ONWnhMC9ILeqd5GURt9hgFbT8J5HsA7wODgu99KamnMGU6tWZ3VmbejdHerpUP9avrkTyXANYg5dLbfdfziZnGTsjzNe1fIRJoCZ/B90IIJM7vs34Pp9OjbGaR2yK2DShd6G2fDX6IhFhIj8eUQzMb9K46dLM48osLsICAjVBmnICHi1FR2IAlYysXDcwX9Nq7D2MQUVku8G8zaYZqNx1Bl6m8aURfI4c6oNYXBZRUGWs018MeeX0AJ96Fmz09P2MH+tWruf2ttKjv073ekhJ06ixAyvsDbJgP6Oye0wzHy6WeTnIzJlOtJ9CblNLyEDEO8gJXNB1+UfjAl7sHlK/Cy+r2BvFYlKLtoE=
  domain: sgss
  app: demo
  on:
    repo: studentisgss/booking
    branch: master
